export const Users = [
    {
      id:1,
      profilePicture: "assets/hello.jpeg",
      username: "Nie&n..",
    },
    {
      id:2,
      profilePicture: "assets/hey.jpg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "assets/3.jpg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "assets/itachi.jpg",
      username: "Dora Hawks",

    },
    {
      id:5,
      profilePicture: "assets/mm.jpeg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "assets/yoo.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "assets/name.jpg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "assets/download.jpeg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "assets/hello.jpeg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "assets/heart.png",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Pictures = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/3.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      dislike:12,
      comment: 9,
      description:"holla"
    },
    {
      id: 2,
      photo: "assets/1.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      dislike:12,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/images.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      dislike:0,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      dislike:12,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/yoo.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      dislike:13,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/3.jpg",
      date: "1 day ago",
      userId: 6,
      dislike:12,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/mm.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      dislike:12,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/hello.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      dislike:12,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/4.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      dislike:12,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/5.jpg",
      date: "1 week ago",
      userId: 10,
      dislike:12,
      like: 104,
      comment: 12,
    },
  ];